hackclub/shipwrecked

components/common/Header.tsx

use thumbs profile

---

app/bay/faq/page.tsx

see https://hackclub.slack.com/archives/C08N0R86DMJ/p1747107813325149

fix: gh req

---

.env.example
app/api/auth/[...nextauth]/route.ts
lib/loops.ts
package.json
yarn.lock

- use loops for sending sign-in emails
- remove dependency on `nodemailer`

use loops for sending authentication email

---

app/admin/projects/page.tsx
app/admin/users/page.tsx
app/bay/intro/register/page.tsx

fixing build

---

app/bay/page.tsx
app/faq/page.tsx

Update progress bar copy to be accurate

Update progress bar copy to be accurate

---

app/api/projects/route.ts

Fixes one of the two vulnerabilities I found.

Disallow non-admins from changing sensitive project fields

---

.gitignore
webhook-forwarder/Dockerfile
webhook-forwarder/README.md
webhook-forwarder/package-lock.json
webhook-forwarder/package.json
webhook-forwarder/server.js

add app to intercept/modify/forward webhooks from coolify for shipwrecked slack notifications

add webhook-forwarder app

---

app/bay/page.tsx

fixed viral projects counting as 15 hours

---

app/admin/users/[userId]/page.tsx

Add grey bg and restrict width of dropdowns on manage user page

---

app/bay/page.module.css
app/bay/page.tsx

Fix project edit menu overflowing on bottom

---

app/api/projects/route.ts
yarn.lock

Expanded reviewer permissions to update project fields and audit changes. (So you dont need to be an admin to do that.)

expand reviewer permissions to update project fields and audit changes.

---

app/admin/users/page.tsx
app/api/admin/users/route.ts
app/bay/page.tsx

Show user progress on admin page

---

app/api/users/me/route.ts
app/review/page.tsx
components/common/UserCategoryBadge.tsx

Adding hackatime to the review flow

Adding hackatime to the review flow

---

app/api/reviews/route.ts
app/review/page.tsx
components/common/ReviewSection.tsx

allows reviewers to leave comments without giving a decision on the review

adding comment as review option

---

app/info/travel/page.mdx

fixing #369 (this is mb i wrote that text)

changing 'landing' to 'leaving' on flight info page

---

app/admin/users/[userId]/page.tsx
app/admin/users/page.tsx
app/bay/page.tsx
lib/project-client.ts
lib/project.test.ts
lib/project.ts
metrics.ts
package.json
pipelines/Dockerfile
pipelines/jobs/airtable-rsvp/update-airtable-rsvp.ts
prisma/schema.prisma

This contains many unit tests that hope to exercise the logic we want for accurate island progress tracking

Add additional airtable data relating to island progress, and fix bugs in progress calculations

---

app/admin/projects/page.tsx

it wasnt scrolling inside before

making admin edit project tab scroll

---

pipelines/jobs/airtable-sync/index.ts
pipelines/pipeline-prisma.ts

Pipeline was failing due bad import statement and env configs not changed.

Airtable sync pipeline update

---

app/bay/page.tsx

This issue (see image) is now fixed by making overflow scroll and setting a max height of the screen height.

Fix bottom overflow on project detail view on /bay

---

app/api/hackatime/user-stats/route.ts
components/common/HackatimeLanguageStats.tsx
components/common/ReviewSection.tsx

Fixes the per user to go to a per project stats

Add per project lang stats

---

components/common/Header.tsx

Add leaderboard tab on mobile menu

fix(Header): Add "Leaderboard" tab on mobile menu

---

lib/shop-utils.ts

Changing the price randomization algorithm to use SHA256 instead of a hand-rolled hash solves the issue of prices remaining mostly fixed for a user over time, and guarantees that random prices are evenly distributed and fair for all users.
See [this #meta thread](https://hackclub.slack.com/archives/C0188CY57PZ/p1753115796754259?thread_ts=1753068899.845589&cid=C0188CY57PZ)
have a great day :)

Change price randomization algorithm to use SHA256

---

app/admin/users/[userId]/page.tsx

use overall approved hours in admin user view

---

app/admin/users/[userId]/page.tsx
app/api/auth/[...nextauth]/route.ts
app/bay/page.tsx
app/bay/tooltip.module.css
components/common/Tooltip.tsx

Improve tooltips for clarity
